/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as BancaRouteImport } from './routes/banca'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellTeamRouteImport } from './routes/_authenticated/_shell/team'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell/settings'
import { Route as AuthenticatedShellDevelopersRouteImport } from './routes/_authenticated/_shell/developers'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell/dashboard'
import { Route as AuthenticatedShellContactsRouteImport } from './routes/_authenticated/_shell/contacts'
import { Route as AuthenticatedShellAuditLogRouteImport } from './routes/_authenticated/_shell/audit-log'
import { Route as AuthenticatedShellAnalyticsRouteImport } from './routes/_authenticated/_shell/analytics'
import { Route as AuthenticatedShellCampaignsIndexRouteImport } from './routes/_authenticated/_shell/campaigns.index'
import { Route as AuthenticatedShellCampaignsNewRouteImport } from './routes/_authenticated/_shell/campaigns.new'
import { Route as AuthenticatedShellCampaignsIdIndexRouteImport } from './routes/_authenticated/_shell/campaigns.$id.index'
import { Route as AuthenticatedShellCampaignsIdQueueRouteImport } from './routes/_authenticated/_shell/campaigns.$id.queue'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const BancaRoute = BancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellTeamRoute = AuthenticatedShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDevelopersRoute =
  AuthenticatedShellDevelopersRouteImport.update({
    id: '/developers',
    path: '/developers',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellContactsRoute =
  AuthenticatedShellContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAuditLogRoute =
  AuthenticatedShellAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAnalyticsRoute =
  AuthenticatedShellAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsIndexRoute =
  AuthenticatedShellCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsNewRoute =
  AuthenticatedShellCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsIdIndexRoute =
  AuthenticatedShellCampaignsIdIndexRouteImport.update({
    id: '/campaigns/$id/',
    path: '/campaigns/$id/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsIdQueueRoute =
  AuthenticatedShellCampaignsIdQueueRouteImport.update({
    id: '/campaigns/$id/queue',
    path: '/campaigns/$id/queue',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/retail': typeof RetailRoute
  '/seguros': typeof SegurosRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styleguide': typeof StyleguideRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/audit-log': typeof AuthenticatedShellAuditLogRoute
  '/contacts': typeof AuthenticatedShellContactsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/developers': typeof AuthenticatedShellDevelopersRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/team': typeof AuthenticatedShellTeamRoute
  '/campaigns/new': typeof AuthenticatedShellCampaignsNewRoute
  '/campaigns/': typeof AuthenticatedShellCampaignsIndexRoute
  '/campaigns/$id/queue': typeof AuthenticatedShellCampaignsIdQueueRoute
  '/campaigns/$id/': typeof AuthenticatedShellCampaignsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/retail': typeof RetailRoute
  '/seguros': typeof SegurosRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styleguide': typeof StyleguideRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/audit-log': typeof AuthenticatedShellAuditLogRoute
  '/contacts': typeof AuthenticatedShellContactsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/developers': typeof AuthenticatedShellDevelopersRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/team': typeof AuthenticatedShellTeamRoute
  '/campaigns/new': typeof AuthenticatedShellCampaignsNewRoute
  '/campaigns': typeof AuthenticatedShellCampaignsIndexRoute
  '/campaigns/$id/queue': typeof AuthenticatedShellCampaignsIdQueueRoute
  '/campaigns/$id': typeof AuthenticatedShellCampaignsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/banca': typeof BancaRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/retail': typeof RetailRoute
  '/seguros': typeof SegurosRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styleguide': typeof StyleguideRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_shell/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/_authenticated/_shell/audit-log': typeof AuthenticatedShellAuditLogRoute
  '/_authenticated/_shell/contacts': typeof AuthenticatedShellContactsRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/developers': typeof AuthenticatedShellDevelopersRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
  '/_authenticated/_shell/team': typeof AuthenticatedShellTeamRoute
  '/_authenticated/_shell/campaigns/new': typeof AuthenticatedShellCampaignsNewRoute
  '/_authenticated/_shell/campaigns/': typeof AuthenticatedShellCampaignsIndexRoute
  '/_authenticated/_shell/campaigns/$id/queue': typeof AuthenticatedShellCampaignsIdQueueRoute
  '/_authenticated/_shell/campaigns/$id/': typeof AuthenticatedShellCampaignsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banca'
    | '/delivery'
    | '/login'
    | '/retail'
    | '/seguros'
    | '/signup'
    | '/sitemap.xml'
    | '/styleguide'
    | '/onboarding'
    | '/analytics'
    | '/audit-log'
    | '/contacts'
    | '/dashboard'
    | '/developers'
    | '/settings'
    | '/team'
    | '/campaigns/new'
    | '/campaigns/'
    | '/campaigns/$id/queue'
    | '/campaigns/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banca'
    | '/delivery'
    | '/login'
    | '/retail'
    | '/seguros'
    | '/signup'
    | '/sitemap.xml'
    | '/styleguide'
    | '/onboarding'
    | '/analytics'
    | '/audit-log'
    | '/contacts'
    | '/dashboard'
    | '/developers'
    | '/settings'
    | '/team'
    | '/campaigns/new'
    | '/campaigns'
    | '/campaigns/$id/queue'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/banca'
    | '/delivery'
    | '/login'
    | '/retail'
    | '/seguros'
    | '/signup'
    | '/sitemap.xml'
    | '/styleguide'
    | '/_authenticated/_shell'
    | '/_authenticated/onboarding'
    | '/_authenticated/_shell/analytics'
    | '/_authenticated/_shell/audit-log'
    | '/_authenticated/_shell/contacts'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/developers'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/team'
    | '/_authenticated/_shell/campaigns/new'
    | '/_authenticated/_shell/campaigns/'
    | '/_authenticated/_shell/campaigns/$id/queue'
    | '/_authenticated/_shell/campaigns/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BancaRoute: typeof BancaRoute
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  RetailRoute: typeof RetailRoute
  SegurosRoute: typeof SegurosRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StyleguideRoute: typeof StyleguideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banca': {
      id: '/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof BancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/team': {
      id: '/_authenticated/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedShellTeamRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/developers': {
      id: '/_authenticated/_shell/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof AuthenticatedShellDevelopersRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/contacts': {
      id: '/_authenticated/_shell/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedShellContactsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/audit-log': {
      id: '/_authenticated/_shell/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedShellAuditLogRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/analytics': {
      id: '/_authenticated/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedShellAnalyticsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/': {
      id: '/_authenticated/_shell/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/new': {
      id: '/_authenticated/_shell/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedShellCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/$id/': {
      id: '/_authenticated/_shell/campaigns/$id/'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id/'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIdIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/$id/queue': {
      id: '/_authenticated/_shell/campaigns/$id/queue'
      path: '/campaigns/$id/queue'
      fullPath: '/campaigns/$id/queue'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIdQueueRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAnalyticsRoute: typeof AuthenticatedShellAnalyticsRoute
  AuthenticatedShellAuditLogRoute: typeof AuthenticatedShellAuditLogRoute
  AuthenticatedShellContactsRoute: typeof AuthenticatedShellContactsRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellDevelopersRoute: typeof AuthenticatedShellDevelopersRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
  AuthenticatedShellTeamRoute: typeof AuthenticatedShellTeamRoute
  AuthenticatedShellCampaignsNewRoute: typeof AuthenticatedShellCampaignsNewRoute
  AuthenticatedShellCampaignsIndexRoute: typeof AuthenticatedShellCampaignsIndexRoute
  AuthenticatedShellCampaignsIdQueueRoute: typeof AuthenticatedShellCampaignsIdQueueRoute
  AuthenticatedShellCampaignsIdIndexRoute: typeof AuthenticatedShellCampaignsIdIndexRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAnalyticsRoute: AuthenticatedShellAnalyticsRoute,
  AuthenticatedShellAuditLogRoute: AuthenticatedShellAuditLogRoute,
  AuthenticatedShellContactsRoute: AuthenticatedShellContactsRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellDevelopersRoute: AuthenticatedShellDevelopersRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
  AuthenticatedShellTeamRoute: AuthenticatedShellTeamRoute,
  AuthenticatedShellCampaignsNewRoute: AuthenticatedShellCampaignsNewRoute,
  AuthenticatedShellCampaignsIndexRoute: AuthenticatedShellCampaignsIndexRoute,
  AuthenticatedShellCampaignsIdQueueRoute:
    AuthenticatedShellCampaignsIdQueueRoute,
  AuthenticatedShellCampaignsIdIndexRoute:
    AuthenticatedShellCampaignsIdIndexRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BancaRoute: BancaRoute,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  RetailRoute: RetailRoute,
  SegurosRoute: SegurosRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StyleguideRoute: StyleguideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
