/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelcoRouteImport } from './routes/telco'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as BancaRouteImport } from './routes/banca'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayTokenRouteImport } from './routes/play.$token'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellTeamRouteImport } from './routes/_authenticated/_shell/team'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell/settings'
import { Route as AuthenticatedShellDevelopersRouteImport } from './routes/_authenticated/_shell/developers'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell/dashboard'
import { Route as AuthenticatedShellContactsRouteImport } from './routes/_authenticated/_shell/contacts'
import { Route as AuthenticatedShellAuditLogRouteImport } from './routes/_authenticated/_shell/audit-log'
import { Route as AuthenticatedShellAudiencesRouteImport } from './routes/_authenticated/_shell/audiences'
import { Route as AuthenticatedShellAnalyticsRouteImport } from './routes/_authenticated/_shell/analytics'
import { Route as AuthenticatedShellAdminRouteImport } from './routes/_authenticated/_shell/admin'
import { Route as AuthenticatedShellSettingsIndexRouteImport } from './routes/_authenticated/_shell/settings.index'
import { Route as AuthenticatedShellCampaignsIndexRouteImport } from './routes/_authenticated/_shell/campaigns.index'
import { Route as AuthenticatedShellAdminIndexRouteImport } from './routes/_authenticated/_shell/admin/index'
import { Route as AuthenticatedShellSettingsSenderRouteImport } from './routes/_authenticated/_shell/settings.sender'
import { Route as AuthenticatedShellSettingsProvidersRouteImport } from './routes/_authenticated/_shell/settings.providers'
import { Route as AuthenticatedShellSettingsBillingRouteImport } from './routes/_authenticated/_shell/settings.billing'
import { Route as AuthenticatedShellCampaignsNewRouteImport } from './routes/_authenticated/_shell/campaigns.new'
import { Route as AuthenticatedShellCampaignsIdIndexRouteImport } from './routes/_authenticated/_shell/campaigns.$id.index'
import { Route as AuthenticatedShellCampaignsIdQueueRouteImport } from './routes/_authenticated/_shell/campaigns.$id.queue'
import { Route as AuthenticatedShellCampaignsIdEditRouteImport } from './routes/_authenticated/_shell/campaigns.$id.edit'
import { Route as AuthenticatedShellAdminTenantsIdRouteImport } from './routes/_authenticated/_shell/admin/tenants.$id'

const TelcoRoute = TelcoRouteImport.update({
  id: '/telco',
  path: '/telco',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const BancaRoute = BancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTokenRoute = PlayTokenRouteImport.update({
  id: '/play/$token',
  path: '/play/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellTeamRoute = AuthenticatedShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDevelopersRoute =
  AuthenticatedShellDevelopersRouteImport.update({
    id: '/developers',
    path: '/developers',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellContactsRoute =
  AuthenticatedShellContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAuditLogRoute =
  AuthenticatedShellAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAudiencesRoute =
  AuthenticatedShellAudiencesRouteImport.update({
    id: '/audiences',
    path: '/audiences',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAnalyticsRoute =
  AuthenticatedShellAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAdminRoute = AuthenticatedShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellSettingsIndexRoute =
  AuthenticatedShellSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellCampaignsIndexRoute =
  AuthenticatedShellCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAdminIndexRoute =
  AuthenticatedShellAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShellAdminRoute,
  } as any)
const AuthenticatedShellSettingsSenderRoute =
  AuthenticatedShellSettingsSenderRouteImport.update({
    id: '/sender',
    path: '/sender',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellSettingsProvidersRoute =
  AuthenticatedShellSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellSettingsBillingRoute =
  AuthenticatedShellSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellCampaignsNewRoute =
  AuthenticatedShellCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsIdIndexRoute =
  AuthenticatedShellCampaignsIdIndexRouteImport.update({
    id: '/campaigns/$id/',
    path: '/campaigns/$id/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsIdQueueRoute =
  AuthenticatedShellCampaignsIdQueueRouteImport.update({
    id: '/campaigns/$id/queue',
    path: '/campaigns/$id/queue',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsIdEditRoute =
  AuthenticatedShellCampaignsIdEditRouteImport.update({
    id: '/campaigns/$id/edit',
    path: '/campaigns/$id/edit',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAdminTenantsIdRoute =
  AuthenticatedShellAdminTenantsIdRouteImport.update({
    id: '/tenants/$id',
    path: '/tenants/$id',
    getParentRoute: () => AuthenticatedShellAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/retail': typeof RetailRoute
  '/seguros': typeof SegurosRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styleguide': typeof StyleguideRoute
  '/telco': typeof TelcoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/play/$token': typeof PlayTokenRoute
  '/admin': typeof AuthenticatedShellAdminRouteWithChildren
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/audiences': typeof AuthenticatedShellAudiencesRoute
  '/audit-log': typeof AuthenticatedShellAuditLogRoute
  '/contacts': typeof AuthenticatedShellContactsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/developers': typeof AuthenticatedShellDevelopersRoute
  '/settings': typeof AuthenticatedShellSettingsRouteWithChildren
  '/team': typeof AuthenticatedShellTeamRoute
  '/campaigns/new': typeof AuthenticatedShellCampaignsNewRoute
  '/settings/billing': typeof AuthenticatedShellSettingsBillingRoute
  '/settings/providers': typeof AuthenticatedShellSettingsProvidersRoute
  '/settings/sender': typeof AuthenticatedShellSettingsSenderRoute
  '/admin/': typeof AuthenticatedShellAdminIndexRoute
  '/campaigns/': typeof AuthenticatedShellCampaignsIndexRoute
  '/settings/': typeof AuthenticatedShellSettingsIndexRoute
  '/admin/tenants/$id': typeof AuthenticatedShellAdminTenantsIdRoute
  '/campaigns/$id/edit': typeof AuthenticatedShellCampaignsIdEditRoute
  '/campaigns/$id/queue': typeof AuthenticatedShellCampaignsIdQueueRoute
  '/campaigns/$id/': typeof AuthenticatedShellCampaignsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/retail': typeof RetailRoute
  '/seguros': typeof SegurosRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styleguide': typeof StyleguideRoute
  '/telco': typeof TelcoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/play/$token': typeof PlayTokenRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/audiences': typeof AuthenticatedShellAudiencesRoute
  '/audit-log': typeof AuthenticatedShellAuditLogRoute
  '/contacts': typeof AuthenticatedShellContactsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/developers': typeof AuthenticatedShellDevelopersRoute
  '/team': typeof AuthenticatedShellTeamRoute
  '/campaigns/new': typeof AuthenticatedShellCampaignsNewRoute
  '/settings/billing': typeof AuthenticatedShellSettingsBillingRoute
  '/settings/providers': typeof AuthenticatedShellSettingsProvidersRoute
  '/settings/sender': typeof AuthenticatedShellSettingsSenderRoute
  '/admin': typeof AuthenticatedShellAdminIndexRoute
  '/campaigns': typeof AuthenticatedShellCampaignsIndexRoute
  '/settings': typeof AuthenticatedShellSettingsIndexRoute
  '/admin/tenants/$id': typeof AuthenticatedShellAdminTenantsIdRoute
  '/campaigns/$id/edit': typeof AuthenticatedShellCampaignsIdEditRoute
  '/campaigns/$id/queue': typeof AuthenticatedShellCampaignsIdQueueRoute
  '/campaigns/$id': typeof AuthenticatedShellCampaignsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/banca': typeof BancaRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/retail': typeof RetailRoute
  '/seguros': typeof SegurosRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styleguide': typeof StyleguideRoute
  '/telco': typeof TelcoRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/play/$token': typeof PlayTokenRoute
  '/_authenticated/_shell/admin': typeof AuthenticatedShellAdminRouteWithChildren
  '/_authenticated/_shell/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/_authenticated/_shell/audiences': typeof AuthenticatedShellAudiencesRoute
  '/_authenticated/_shell/audit-log': typeof AuthenticatedShellAuditLogRoute
  '/_authenticated/_shell/contacts': typeof AuthenticatedShellContactsRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/developers': typeof AuthenticatedShellDevelopersRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRouteWithChildren
  '/_authenticated/_shell/team': typeof AuthenticatedShellTeamRoute
  '/_authenticated/_shell/campaigns/new': typeof AuthenticatedShellCampaignsNewRoute
  '/_authenticated/_shell/settings/billing': typeof AuthenticatedShellSettingsBillingRoute
  '/_authenticated/_shell/settings/providers': typeof AuthenticatedShellSettingsProvidersRoute
  '/_authenticated/_shell/settings/sender': typeof AuthenticatedShellSettingsSenderRoute
  '/_authenticated/_shell/admin/': typeof AuthenticatedShellAdminIndexRoute
  '/_authenticated/_shell/campaigns/': typeof AuthenticatedShellCampaignsIndexRoute
  '/_authenticated/_shell/settings/': typeof AuthenticatedShellSettingsIndexRoute
  '/_authenticated/_shell/admin/tenants/$id': typeof AuthenticatedShellAdminTenantsIdRoute
  '/_authenticated/_shell/campaigns/$id/edit': typeof AuthenticatedShellCampaignsIdEditRoute
  '/_authenticated/_shell/campaigns/$id/queue': typeof AuthenticatedShellCampaignsIdQueueRoute
  '/_authenticated/_shell/campaigns/$id/': typeof AuthenticatedShellCampaignsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banca'
    | '/delivery'
    | '/login'
    | '/retail'
    | '/seguros'
    | '/signup'
    | '/sitemap.xml'
    | '/styleguide'
    | '/telco'
    | '/onboarding'
    | '/play/$token'
    | '/admin'
    | '/analytics'
    | '/audiences'
    | '/audit-log'
    | '/contacts'
    | '/dashboard'
    | '/developers'
    | '/settings'
    | '/team'
    | '/campaigns/new'
    | '/settings/billing'
    | '/settings/providers'
    | '/settings/sender'
    | '/admin/'
    | '/campaigns/'
    | '/settings/'
    | '/admin/tenants/$id'
    | '/campaigns/$id/edit'
    | '/campaigns/$id/queue'
    | '/campaigns/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banca'
    | '/delivery'
    | '/login'
    | '/retail'
    | '/seguros'
    | '/signup'
    | '/sitemap.xml'
    | '/styleguide'
    | '/telco'
    | '/onboarding'
    | '/play/$token'
    | '/analytics'
    | '/audiences'
    | '/audit-log'
    | '/contacts'
    | '/dashboard'
    | '/developers'
    | '/team'
    | '/campaigns/new'
    | '/settings/billing'
    | '/settings/providers'
    | '/settings/sender'
    | '/admin'
    | '/campaigns'
    | '/settings'
    | '/admin/tenants/$id'
    | '/campaigns/$id/edit'
    | '/campaigns/$id/queue'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/banca'
    | '/delivery'
    | '/login'
    | '/retail'
    | '/seguros'
    | '/signup'
    | '/sitemap.xml'
    | '/styleguide'
    | '/telco'
    | '/_authenticated/_shell'
    | '/_authenticated/onboarding'
    | '/play/$token'
    | '/_authenticated/_shell/admin'
    | '/_authenticated/_shell/analytics'
    | '/_authenticated/_shell/audiences'
    | '/_authenticated/_shell/audit-log'
    | '/_authenticated/_shell/contacts'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/developers'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/team'
    | '/_authenticated/_shell/campaigns/new'
    | '/_authenticated/_shell/settings/billing'
    | '/_authenticated/_shell/settings/providers'
    | '/_authenticated/_shell/settings/sender'
    | '/_authenticated/_shell/admin/'
    | '/_authenticated/_shell/campaigns/'
    | '/_authenticated/_shell/settings/'
    | '/_authenticated/_shell/admin/tenants/$id'
    | '/_authenticated/_shell/campaigns/$id/edit'
    | '/_authenticated/_shell/campaigns/$id/queue'
    | '/_authenticated/_shell/campaigns/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BancaRoute: typeof BancaRoute
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  RetailRoute: typeof RetailRoute
  SegurosRoute: typeof SegurosRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StyleguideRoute: typeof StyleguideRoute
  TelcoRoute: typeof TelcoRoute
  PlayTokenRoute: typeof PlayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telco': {
      id: '/telco'
      path: '/telco'
      fullPath: '/telco'
      preLoaderRoute: typeof TelcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banca': {
      id: '/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof BancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$token': {
      id: '/play/$token'
      path: '/play/$token'
      fullPath: '/play/$token'
      preLoaderRoute: typeof PlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/team': {
      id: '/_authenticated/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedShellTeamRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/developers': {
      id: '/_authenticated/_shell/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof AuthenticatedShellDevelopersRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/contacts': {
      id: '/_authenticated/_shell/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedShellContactsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/audit-log': {
      id: '/_authenticated/_shell/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedShellAuditLogRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/audiences': {
      id: '/_authenticated/_shell/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AuthenticatedShellAudiencesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/analytics': {
      id: '/_authenticated/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedShellAnalyticsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/admin': {
      id: '/_authenticated/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedShellAdminRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/': {
      id: '/_authenticated/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedShellSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/campaigns/': {
      id: '/_authenticated/_shell/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/admin/': {
      id: '/_authenticated/_shell/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedShellAdminIndexRouteImport
      parentRoute: typeof AuthenticatedShellAdminRoute
    }
    '/_authenticated/_shell/settings/sender': {
      id: '/_authenticated/_shell/settings/sender'
      path: '/sender'
      fullPath: '/settings/sender'
      preLoaderRoute: typeof AuthenticatedShellSettingsSenderRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/settings/providers': {
      id: '/_authenticated/_shell/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AuthenticatedShellSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/settings/billing': {
      id: '/_authenticated/_shell/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedShellSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/campaigns/new': {
      id: '/_authenticated/_shell/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedShellCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/$id/': {
      id: '/_authenticated/_shell/campaigns/$id/'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id/'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIdIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/$id/queue': {
      id: '/_authenticated/_shell/campaigns/$id/queue'
      path: '/campaigns/$id/queue'
      fullPath: '/campaigns/$id/queue'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIdQueueRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns/$id/edit': {
      id: '/_authenticated/_shell/campaigns/$id/edit'
      path: '/campaigns/$id/edit'
      fullPath: '/campaigns/$id/edit'
      preLoaderRoute: typeof AuthenticatedShellCampaignsIdEditRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/admin/tenants/$id': {
      id: '/_authenticated/_shell/admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AuthenticatedShellAdminTenantsIdRouteImport
      parentRoute: typeof AuthenticatedShellAdminRoute
    }
  }
}

interface AuthenticatedShellAdminRouteChildren {
  AuthenticatedShellAdminIndexRoute: typeof AuthenticatedShellAdminIndexRoute
  AuthenticatedShellAdminTenantsIdRoute: typeof AuthenticatedShellAdminTenantsIdRoute
}

const AuthenticatedShellAdminRouteChildren: AuthenticatedShellAdminRouteChildren =
  {
    AuthenticatedShellAdminIndexRoute: AuthenticatedShellAdminIndexRoute,
    AuthenticatedShellAdminTenantsIdRoute:
      AuthenticatedShellAdminTenantsIdRoute,
  }

const AuthenticatedShellAdminRouteWithChildren =
  AuthenticatedShellAdminRoute._addFileChildren(
    AuthenticatedShellAdminRouteChildren,
  )

interface AuthenticatedShellSettingsRouteChildren {
  AuthenticatedShellSettingsBillingRoute: typeof AuthenticatedShellSettingsBillingRoute
  AuthenticatedShellSettingsProvidersRoute: typeof AuthenticatedShellSettingsProvidersRoute
  AuthenticatedShellSettingsSenderRoute: typeof AuthenticatedShellSettingsSenderRoute
  AuthenticatedShellSettingsIndexRoute: typeof AuthenticatedShellSettingsIndexRoute
}

const AuthenticatedShellSettingsRouteChildren: AuthenticatedShellSettingsRouteChildren =
  {
    AuthenticatedShellSettingsBillingRoute:
      AuthenticatedShellSettingsBillingRoute,
    AuthenticatedShellSettingsProvidersRoute:
      AuthenticatedShellSettingsProvidersRoute,
    AuthenticatedShellSettingsSenderRoute:
      AuthenticatedShellSettingsSenderRoute,
    AuthenticatedShellSettingsIndexRoute: AuthenticatedShellSettingsIndexRoute,
  }

const AuthenticatedShellSettingsRouteWithChildren =
  AuthenticatedShellSettingsRoute._addFileChildren(
    AuthenticatedShellSettingsRouteChildren,
  )

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAdminRoute: typeof AuthenticatedShellAdminRouteWithChildren
  AuthenticatedShellAnalyticsRoute: typeof AuthenticatedShellAnalyticsRoute
  AuthenticatedShellAudiencesRoute: typeof AuthenticatedShellAudiencesRoute
  AuthenticatedShellAuditLogRoute: typeof AuthenticatedShellAuditLogRoute
  AuthenticatedShellContactsRoute: typeof AuthenticatedShellContactsRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellDevelopersRoute: typeof AuthenticatedShellDevelopersRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRouteWithChildren
  AuthenticatedShellTeamRoute: typeof AuthenticatedShellTeamRoute
  AuthenticatedShellCampaignsNewRoute: typeof AuthenticatedShellCampaignsNewRoute
  AuthenticatedShellCampaignsIndexRoute: typeof AuthenticatedShellCampaignsIndexRoute
  AuthenticatedShellCampaignsIdEditRoute: typeof AuthenticatedShellCampaignsIdEditRoute
  AuthenticatedShellCampaignsIdQueueRoute: typeof AuthenticatedShellCampaignsIdQueueRoute
  AuthenticatedShellCampaignsIdIndexRoute: typeof AuthenticatedShellCampaignsIdIndexRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAdminRoute: AuthenticatedShellAdminRouteWithChildren,
  AuthenticatedShellAnalyticsRoute: AuthenticatedShellAnalyticsRoute,
  AuthenticatedShellAudiencesRoute: AuthenticatedShellAudiencesRoute,
  AuthenticatedShellAuditLogRoute: AuthenticatedShellAuditLogRoute,
  AuthenticatedShellContactsRoute: AuthenticatedShellContactsRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellDevelopersRoute: AuthenticatedShellDevelopersRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRouteWithChildren,
  AuthenticatedShellTeamRoute: AuthenticatedShellTeamRoute,
  AuthenticatedShellCampaignsNewRoute: AuthenticatedShellCampaignsNewRoute,
  AuthenticatedShellCampaignsIndexRoute: AuthenticatedShellCampaignsIndexRoute,
  AuthenticatedShellCampaignsIdEditRoute:
    AuthenticatedShellCampaignsIdEditRoute,
  AuthenticatedShellCampaignsIdQueueRoute:
    AuthenticatedShellCampaignsIdQueueRoute,
  AuthenticatedShellCampaignsIdIndexRoute:
    AuthenticatedShellCampaignsIdIndexRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BancaRoute: BancaRoute,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  RetailRoute: RetailRoute,
  SegurosRoute: SegurosRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StyleguideRoute: StyleguideRoute,
  TelcoRoute: TelcoRoute,
  PlayTokenRoute: PlayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
