/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell/settings'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell/dashboard'
import { Route as AuthenticatedShellContactsRouteImport } from './routes/_authenticated/_shell/contacts'
import { Route as AuthenticatedShellCampaignsRouteImport } from './routes/_authenticated/_shell/campaigns'
import { Route as AuthenticatedShellAnalyticsRouteImport } from './routes/_authenticated/_shell/analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellContactsRoute =
  AuthenticatedShellContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCampaignsRoute =
  AuthenticatedShellCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAnalyticsRoute =
  AuthenticatedShellAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/campaigns': typeof AuthenticatedShellCampaignsRoute
  '/contacts': typeof AuthenticatedShellContactsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/campaigns': typeof AuthenticatedShellCampaignsRoute
  '/contacts': typeof AuthenticatedShellContactsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_shell/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/_authenticated/_shell/campaigns': typeof AuthenticatedShellCampaignsRoute
  '/_authenticated/_shell/contacts': typeof AuthenticatedShellContactsRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/analytics'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/analytics'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_shell'
    | '/_authenticated/onboarding'
    | '/_authenticated/_shell/analytics'
    | '/_authenticated/_shell/campaigns'
    | '/_authenticated/_shell/contacts'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/contacts': {
      id: '/_authenticated/_shell/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedShellContactsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/campaigns': {
      id: '/_authenticated/_shell/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedShellCampaignsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/analytics': {
      id: '/_authenticated/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedShellAnalyticsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAnalyticsRoute: typeof AuthenticatedShellAnalyticsRoute
  AuthenticatedShellCampaignsRoute: typeof AuthenticatedShellCampaignsRoute
  AuthenticatedShellContactsRoute: typeof AuthenticatedShellContactsRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAnalyticsRoute: AuthenticatedShellAnalyticsRoute,
  AuthenticatedShellCampaignsRoute: AuthenticatedShellCampaignsRoute,
  AuthenticatedShellContactsRoute: AuthenticatedShellContactsRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
